### ISSUE TITLE
Problem to install the librarie

### ISSUE THREAD

**Issue by AJP2511** [sparkfun/HX711-Load-Cell-Amplifier#11]
Hello guys.

i'm trying to install the librarie but my IDE just say that:

Arduino: 1.8.6 (Windows 7), Card: "Arduino / Genuine One"

The folder / zip file does not contain the library

This report would have more information
"Show a detailed output during a build"
option can be activated under "File -> Preferences"

someone know how to solve this?

thanks.

**Comment by bboyho** [comment]
Hi,

I just noticed this issue when looking at the repository. I usually do a search for the library if it is not included in the example code or linked to the Arduino Library Manager. However, the library is linked in the tutorial here => [https://learn.sparkfun.com/tutorials/load-cell-amplifier-hx711-breakout-hookup-guide#arduino-code](https://learn.sparkfun.com/tutorials/load-cell-amplifier-hx711-breakout-hookup-guide#arduino-code). You will need to manually install the [HX711 library](https://github.com/bogde/HX711). I recommend looking at this tutorial to [manually install the library](https://learn.sparkfun.com/tutorials/installing-an-arduino-library#manually-installing-a-library---windows) .
