### ISSUE TITLE
Example doesn't match with tutorial

### ISSUE THREAD

**Issue by fahad80** [sparkfun/HX711-Load-Cell-Amplifier#12]
For example, when downloaded the code from this repo and ran the 'SparkFun_HX711_Calibration.ino' it said there aren't any matching function for:
` HX711 scale(DOUT, CLK);`

So I had to copy the code from the [tutorial](https://learn.sparkfun.com/tutorials/load-cell-amplifier-hx711-breakout-hookup-guide).

**Comment by nseidle** [comment]
I should have checked winksaville's pr. He fixed it, but I just redid it all. Anyway, examples should be fixed now. Let me know if something is still not right.
