### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by GoncaloFelicio** [sparkfun/HX711-Load-Cell-Amplifier#14]
Hi!
I would like to know more about calibration. Is specific, does the setup influence the calibration factor, or is the calibration factor a number i get from the calibration sketch and then i always use that same calibration factor? 

In my case, i want to setup 4 loadcells to the same wood board, but can i calibrate before i screw them to the board, or can i only calibrate after i have my setup?

Thanks!

**Comment by santaimpersonator** [comment]
Hi there, it sounds like you are looking for [technical assistance](https://www.sparkfun.com/technical_assistance). Unfortunately, this is not the place to get technical support; it is for filing problems with the code, library, or hardware. Use the link (above), to get started with posting a topic in our [forums](https://forum.sparkfun.com/). Our technical support team will do their best to assist you.

That being said, please check out the guides associated with this product:

- [Load Cell Amplifier HX711 Breakout Hookup Guide](https://learn.sparkfun.com/tutorials/load-cell-amplifier-hx711-breakout-hookup-guide)
- [Getting Started with Load Cells](https://learn.sparkfun.com/tutorials/getting-started-with-load-cells)
