### ISSUE TITLE
how to select  10 sps or 80 sps data output?

### ISSUE THREAD

**Issue by nayanagg** [sparkfun/HX711-Load-Cell-Amplifier#15]
Hi,

i want to know default sps of hx711 and also the procedure to select 80 sps from hx711.

**Comment by mhaboali** [comment]
@nayanagg 
I have the same issue here, have you figured it out?

**Comment by nseidle** [comment]
Please see the HX711 library repo for more info: https://github.com/bogde/HX711

I don't immediately see a method for controlling the SPS: https://github.com/bogde/HX711/blob/master/src/HX711.h
